apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
spec:
  match:
    - excludedNamespaces: ["kube-system", "gatekeeper-system"]
      processes: ["*"]
  sync:
    syncOnly:
      - version: "v1"
        kind: "Namespace"
      - group: "extensions"
        version: "v1beta1"
        kind: "Ingress"
      - group: "networking.k8s.io"
        version: "v1beta1"
        kind: "Ingress"
      - group: "batch"
        version: "v1beta1"
        kind: "CronJob"
      - group: "apps"
        version: "v1"
        kind: "DaemonSet"
      - group: "apps"
        version: "v1"
        kind: "Deployment"
      - group: "batch"
        version: "v1"
        kind: "Job"
      - group: "apps"
        version: "v1"
        kind: "ReplicaSet"
      - version: "v1"
        kind: "ReplicationController"
      - group: "apps"
        version: "v1"
        kind: "StatefulSet"
