apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
    name: demo-app
spec:
    stages:
        - name: production
          cluster:
            repository: https://github.com/enrique-ochoa/aks-gitops.git
            name: cluster1
          resources:
            path: cluster/namespaces/demo-app
          targetNamespace: demo-app
